name: study_abroad
description: "IEC - Premium Education Counselling App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^14.8.1

  # HTTP Client
  dio: ^5.7.0

  # State Management
  provider: ^6.1.2

  # Secure Storage (JWT)
  flutter_secure_storage: ^10.3.1

  # Animations
  flutter_animate: ^4.5.2

  # Google Fonts
  google_fonts: ^6.2.1

  # Image handling
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2

  # URL Launcher (WhatsApp, links)
  url_launcher: ^6.3.1

  # Flags
  country_flags: ^3.0.0

  # Icons
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0

  # Toast notifications
  fluttertoast: ^8.2.14

  # Date formatting
  intl: ^0.19.0

  # Socket.IO
  socket_io_client: ^2.0.3+1

  # Native Video (WebRTC)
  permission_handler: ^11.3.1

  # Shimmer loading
  shimmer: ^3.0.0
  razorpay_flutter: ^1.4.4
  flutter_webrtc: ^1.4.1
  root_checker_plus: ^1.0.0
  flutter_windowmanager: ^0.2.0
  local_auth: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
  assets:
    - assets/icons/
    - assets/images/
    - assets/data/universities.json
    - assets/data/countries/
    - assets/data/scolarship.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_iec.png"
  min_sdk_android: 21