class ServiceModel {
  final String slug;
  final String title;
  final String icon;
  final double price;
  final String description;
  final List<String> features;
  final String? longDescription;

  ServiceModel({
    required this.slug,
    required this.title,
    required this.icon,
    required this.price,
    required this.description,
    required this.features,
    this.longDescription,
  });

  static List<ServiceModel> get allServices => [
    ServiceModel(
      slug: 'consultation',
      title: 'Counselling Session',
      icon: '🎯',
      price: 999,
      description: 'Google Meet session with our counsellors. Get transparency on your case for study/work overseas.',
      features: ['Personalized Advice', 'Case Evaluation', 'Timeline Strategy', 'Adjustable Pricing'],
    ),
    ServiceModel(
      slug: 'research_paper',
      title: 'Research Paper Drafting',
      icon: '📄',
      price: 8999,
      description: 'Publishing credible research papers with your name on them can help boost your profile! Crucial for MS/PhD.',
      features: ['Topic Selection', 'Drafting Support', 'Journal Alignment', 'Publication Help'],
    ),
    ServiceModel(
      slug: 'visa_guidance',
      title: 'Visa Application Help',
      icon: '🛂',
      price: 3499,
      description: 'Ace the visa application through our help in the paperwork, financial planning, and visa interview mock rounds.',
      features: ['Document Checklist', 'Form Filling', 'Interview Prep', 'Mock Sessions'],
    ),
    ServiceModel(
      slug: 'eb1',
      title: 'Apply For An EB-1 Visa',
      icon: '🌟',
      price: 14999,
      description: 'The EB-1 visa is a talent-based immigrant visa in the US for individuals with extraordinary ability.',
      features: ['Eligibility Assessment', 'Evidence Gathering', 'Petition Support', 'Expert Review'],
    ),
    ServiceModel(
      slug: 'application_help',
      title: 'Complete Application Help',
      icon: '📋',
      price: 9999,
      description: 'Get your application into the top 10% of the applications the committee evaluates for admission.',
      features: ['Strategic Planning', 'Document Protocol', 'Submission Portal Help', 'Follow-up Assist'],
    ),
    ServiceModel(
      slug: 'university_shortlist',
      title: 'University Shortlisting',
      icon: '🏛️',
      price: 2999,
      description: 'AI-powered and expert-curated university shortlist tailored to your profile and budget.',
      features: ['Profile Matching', 'Ranking Analysis', 'Budget Fit', '15+ Options'],
    ),
    ServiceModel(
      slug: 'sop_writing',
      title: 'Statement of Purpose Writing',
      icon: '✍️',
      price: 4999,
      description: 'Ivy league graduates work FROM SCRATCH or with your existing draft with unlimited changes.',
      features: ['Professional Editing', 'Unlimited Revisions', 'Plagiarism Free', 'Narrative Design'],
    ),
    ServiceModel(
      slug: 'o1',
      title: 'Apply For An O-1 Visa',
      icon: '🏆',
      price: 12999,
      description: 'The O-1 visa is a talent-based non-immigrant work visa in the US for extraordinary ability.',
      features: ['Talent Profiling', 'Recommendation Help', 'Evidence Strategy', 'Timeline Management'],
    ),
    ServiceModel(
      slug: 'mock_interview',
      title: 'US Visa Mock Interview',
      icon: '🎤',
      price: 1999,
      description: 'The final step to your US visa is a Visa interview. Ace the interview with proven tricks.',
      features: ['Mock Sessions', 'Real scenarios', 'Immediate Feedback', 'Trick Questions Help'],
    ),
    ServiceModel(
      slug: 'lor_drafting',
      title: 'LOR Drafting Support',
      icon: '📝',
      price: 2499,
      description: 'The art of writing exactly what the admissions committee wants to see in an applicant.',
      features: ['Professional Tone', 'Custom Templates', 'Strong Advocacy', 'Impactful Writing'],
    ),
    ServiceModel(
      slug: 'personal_history',
      title: 'Personal History Statement',
      icon: '📖',
      price: 1999,
      description: 'Connect the barriers you have overcome in the past to your current interest in the program.',
      features: ['Storytelling Advice', 'Barrier Highlighting', 'Resilience Proofing', 'Goal Connection'],
    ),
    ServiceModel(
      slug: 'resume_drafting',
      title: 'Resume Drafting',
      icon: '🗂️',
      price: 1499,
      description: 'Learn the secret to a perfect resume that will truly set you apart from any other applicant.',
      features: ['ATS Optimized', 'Layout Design', 'Actionable Bulletpoints', 'Industry Standards'],
    ),
    ServiceModel(
      slug: 'gre_prep',
      title: 'GRE Prep-Plan Building',
      icon: '📊',
      price: 999,
      description: 'The secret to an excellent GRE score is NOT hard work. Get a day-by-day schedule.',
      features: ['Custom Schedule', 'Resource Mapping', 'Cheat-sheets', 'Expert Guidance'],
    ),
    ServiceModel(
      slug: 'university_finalization',
      title: 'University Finalization Help',
      icon: '🎓',
      price: 1999,
      description: 'Need help with finalizing on one? Get a detailed review of the right pick as per your circumstances.',
      features: ['ROI Analysis', 'Location Comparison', 'Job Market Review', 'Final Decision Aide'],
    ),
    ServiceModel(
      slug: 'ai_humanizer',
      title: 'Plagiarism Check Report',
      icon: '🔍',
      price: 499,
      description: 'Use our best-in-class instructor-level Turnitin reporting software to generate reports.',
      features: ['Turnitin Report', 'Detailed Source Breakdown', 'Fast Turnaround', 'Confidential'],
    ),
    ServiceModel(
      slug: 'scholarship_search',
      title: 'Scholarship Application Help',
      icon: '💰',
      price: 3999,
      description: 'Over 60% of our applicants get a scholarship. Join us and secure your funding.',
      features: ['Merit-based Matching', 'Essay Support', 'Financial Planning', 'Expert Tips'],
    ),
    ServiceModel(
      slug: 'toefl_prep',
      title: 'TOEFL Prep-Plan Building',
      icon: '🗣️',
      price: 999,
      description: 'TOEFL scores are your gateway to financial aid. Learn how to score 110+.',
      features: ['Section Strategy', 'Practice Drills', 'Template Provisions', 'Scoring Guide'],
    ),
    ServiceModel(
      slug: 'sop_writing',
      title: 'Canada Visa SOP/LOE',
      icon: '🍁',
      price: 4499,
      description: 'Over 1000 students have been issued permits. We help you ensure success and avoid rejection.',
      features: ['Rejection Reason Analysis', 'LOE Proofing', 'Strong Argument Design', 'Visa Protocol'],
    ),
    ServiceModel(
      slug: 'profile_evaluation',
      title: 'Profile Building Guidance',
      icon: '📈',
      price: 6999,
      description: 'Have more than 3 months of time? Join us for one-on-one mentorship on profile boosting.',
      features: ['Internship Sourcing', 'Activity Planning', 'Skill Map', 'Mentorship'],
    ),
    ServiceModel(
      slug: 'cover_letter',
      title: 'Cover Letter Drafting',
      icon: '✉️',
      price: 1499,
      description: 'Command the attention of top recruiters with a cover letter that makes lasting impressions.',
      features: ['Employer Focused', 'Compelling Writing', 'Role Specific', 'Fast Edits'],
    ),
    ServiceModel(
      slug: 'linkedin_optimization',
      title: 'LinkedIn Profile Boosting',
      icon: '💡',
      price: 2499,
      description: 'Revamp your LinkedIn profile from 0 to 99. Get better admits and job opportunities.',
      features: ['SEO Optimized', 'Banner Design', 'Narrative Help', 'Networking Strategy'],
    ),
    ServiceModel(
      slug: 'express_entry',
      title: 'Express Entry/PNP Help',
      icon: '🍁',
      price: 8999,
      description: 'Canada Permanent Residence (PR) via the Express Entry route. Get filed via experts.',
      features: ['CRS Score Optimization', 'PCC/Medical Guide', 'Documentation protocols', 'Submission Handholding'],
    ),
    ServiceModel(
      slug: 'application_review',
      title: 'Complete Application Review',
      icon: '🔎',
      price: 2999,
      description: 'Sail through your applications with our expertise and ensure success with in-depth reviews.',
      features: ['Third-party Audit', 'Mistake Identification', 'Impact Scoring', 'Final Polish'],
    ),
  ];
}
